version: '3.9'

services:
  db:
    image: postgres:11.0-alpine
    env_file:
      - .db_env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network
  my_app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8000
    env_file:
      - .env
    networks:
      - network
  nginx:
    build: .
    volumes:
      - ./nginx/html /usr/share/nginx/html
    depends_on:
      - my_app
    ports:
      - 8080:80
    networks:
      - network
networks:
  network:
    name: network

volumes:
  pg-data: